movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')), # подключаем веб интерфейс
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls.jwt')),
    path('api/v1/', include('movies.urls')),
]

urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('movie/', views.MovieListView.as_view()),
    path('movie/<int:pk>/', views.MovieDetailView.as_view()),
    path('review/', views.ReviewCreateView.as_view()),
    path('rating/', views.AddStarRatingView.as_view()),
    path('actors/', views.ActorListView.as_view()),
    path('actors/<int:pk>/', views.ActorDetailView.as_view()),
]

movies/models.py
from django.db import models
from datetime import date

from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField('Название', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Actor(models.Model):
    """Актеры"""
    name = models.CharField('Имя', max_length=150)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField('Описание')
    photo = models.ImageField('Изображение', upload_to='actors/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Актеры и режиссеры'
        verbose_name_plural = 'Актеры и режиссеры'


class Genre(models.Model):
    """Жанры"""
    name = models.CharField('Название', max_length=150)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Movie(models.Model):
    """Фильм"""
    title = models.CharField('Название', max_length=150)
    tagline = models.CharField('Слоган', max_length=100, default='')
    description = models.TextField('Описание')
    poster = models.ImageField('Постер', upload_to='movies/')
    year = models.PositiveSmallIntegerField('Дата Выхода', default=2019)
    country = models.CharField('Страна', max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name='режиссер', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='Актеры', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='Жанры')
    world_premiere = models.DateField('Премьера в мире', default=date.today)
    budget = models.PositiveIntegerField('Бюджет', default=0, help_text='Указывать сумму в долларах')
    fees_in_usa = models.PositiveIntegerField(
    'Сборы в США', default=0, help_text='указывать сумму в долларах'
    )

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField('Черновик', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = "Фильмы"

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})


class MovieShots(models.Model):
    title = models.CharField('Заголовк', max_length=160)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, verbose_name="Фильмы", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звезды Рейтинга"""
    value = models.PositiveIntegerField('Значение', default=0)

    def __str__(self):
        return '{}'.format(self.value)

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField('IP aдрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE,
        verbose_name='фильм',
        related_name="ratings"
    )

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = "Рейтинги"


class Review(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True, related_name='children'
    )
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE, related_name='reviews')

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

movies/views.py
from django.db import models
from rest_framework import generics, permissions
from django_filters.rest_framework import DjangoFilterBackend
from .models import Movie, Actor
from .serializers import MovieListSerializer, MovieDetailSerializer, ReviewCreateSerializer, CreateRatingSerializer, \
    ActorListSerializer, ActorDetailSerializer
from .service import get_client_ip, MovieFilter, PaginationMovies


class MovieListView(generics.ListAPIView):
    """ Вывод списка фильмов """
    serializer_class = MovieListSerializer
    filter_backends = (DjangoFilterBackend,)
    filterset_class = MovieFilter
    permission_classes = [permissions.IsAuthenticated] # какие правда доступа должны быть, чтоб просмотреть данный url
    pagination_class = PaginationMovies

    def get_queryset(self):
        movies = Movie.objects.filter(draft=False).annotate(
            rating_user=models.Count("ratings", filter=models.Q(ratings__ip=get_client_ip(self.request)))
        ).annotate(
            middle_star=models.Sum(models.F('ratings__star')) / models.Count(models.F('ratings'))
        )

            # rating_user=models.Case( # придуманное поле, добавляется к каждому объекту Movie
            #     models.When(ratings__ip=get_client_ip(request), then=True),  # если юзер поставил оценку, будет True
            #     default=False,
            #     output_field=models.BooleanField()
        return movies


class MovieDetailView(generics.RetrieveAPIView):
    """ Вывод информации о фильме """
    queryset = Movie.objects.filter(draft=False)
    serializer_class = MovieDetailSerializer


class ActorListView(generics.ListAPIView):
    """ Вывод списка Актеров и Режиссеров """
    queryset = Actor.objects.all()
    serializer_class = ActorListSerializer


class ActorDetailView(generics.RetrieveAPIView):
    """ Вывод информации об Актере или Режиссере """
    queryset = Actor.objects.all()
    serializer_class = ActorDetailSerializer


class ReviewCreateView(generics.CreateAPIView):
    """ Добавление отзыва """
    serializer_class = ReviewCreateSerializer


class AddStarRatingView(generics.CreateAPIView):
    """ Добавление рейтинга к фильму """
    serializer_class = CreateRatingSerializer

    def perform_create(self, serializer):
        serializer.save(ip=get_client_ip(self.request))

movies/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>Clack Website Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
  <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900" rel="stylesheet">
    <!-- //Fonts -->
</head>
<body>
 <div id="page" class="page">
     {% include 'include/header.html' %}
{% block content %}

{% endblock %}
     {% include 'include/footer.html' %}
 </div>

</body>
</html>

movies/templates/include/footer.html
   <!-- footer -->
    <footer class="editContent">
        <div class="container">
            <div class="row footer-top">
                <div class="col-lg-4 footer-grid_section_w3layouts">
                    <h2 class="logo-2 mb-lg-4 mb-3">
                        <a href="index.html" class="editContent">
                                <span class="fa" aria-hidden="true"
                                      style="outline: none; cursor: inherit;">
                                    Django School
                                </span>
                        </a>
                    </h2>
                    <p class="editContent" style="outline: none; cursor: inherit;">
                        Канал для программистов и людей, которые хотят развиваться в сфере IT.
                        Видео уроки по python 3, Django 2, Django 3, JavaScript, Vue.js, HTML, CSS
                        и многое другое.
                    </p>
                    <h4 class="sub-con-fo ad-info my-4 editContent"
                        style="outline: none; cursor: inherit;">Catch on Social</h4>
                    <ul class="w3layouts_social_list media-soc list-unstyled">
                        <li>
                            <a href="#" class="w3pvt_facebook editContent"
                               style="outline: none; cursor: inherit;">
                                <span class="fa fa-facebook-f"
                                      style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="w3pvt_twitter editContent"
                               style="outline: none; cursor: inherit;">
                                <span class="fa fa-twitter"
                                      style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="w3pvt_dribble editContent"
                               style="outline: none; cursor: inherit;">
                                <span class="fa fa-dribbble"
                                      style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="w3pvt_google editContent"
                               style="outline: none; cursor: inherit;">
                                <span class="fa fa-google-plus"
                                      style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-8 footer-right">
                    <div class="w3layouts-news-letter">
                        <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3"
                            style="outline: none; cursor: inherit;">Newsletter</h3>

                        <p class="editContent" style="outline: none; cursor: inherit;">By
                            subscribing to our mailing list you will always get latest news and
                            updates from us.</p>
                        <form action="#" method="post" class="w3layouts-newsletter">
                            <input type="email" name="Email" class="editContent"
                                   placeholder="Enter your email..." required=""
                                   style="outline: none; cursor: inherit;">
                            <button class="btn1 btn" style="outline: none; cursor: inherit;"><span
                                    class="fa fa-paper-plane-o" aria-hidden="true"
                                    style="outline: none; cursor: inherit;"></span></button>

                        </form>
                    </div>
                    <div class="row mt-lg-4 bottom-w3layouts-sec-nav mx-0">
                        <div class="col-md-4 footer-grid_section_w3layouts">
                            <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3"
                                style="outline: none; cursor: inherit;">Разделы</h3>
                            <ul class="list-unstyled w3layouts-icons">
                                <li>
                                    <a href="index.html" class="editContent"
                                       style="outline: none; cursor: inherit;">Главная</a>
                                </li>
                                <li>
                                    <a href="about.html" class="editContent"
                                       style="outline: none; cursor: inherit;">Категории</a>
                                </li>
                                <li>
                                    <a href="contact.html" class="editContent"
                                       style="outline: none; cursor: inherit;">Контакты</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4 footer-grid_section_w3layouts">
                            <!-- social icons -->
                            <div class="agileinfo_social_icons">
                                <h3 class="footer-title text-uppercase editContent mb-lg-4 mb-3"
                                    style="outline: none; cursor: inherit;">Pages</h3>
                                <ul class="list-unstyled w3layouts-icons">

                                    <li>
                                        <a href="#" class="editContent"
                                           style="outline: none; cursor: inherit;">About Us</a>
                                    </li>
                                    <li>
                                        <a href="#" class="editContent"
                                           style="outline: none; cursor: inherit;">About Us</a>
                                    </li>
                                    <li>
                                        <a href="#" class="editContent"
                                           style="outline: none; cursor: inherit;">About Us</a>
                                    </li>
                                    <li>
                                        <a href="#" class="editContent"
                                           style="outline: none; cursor: inherit;">About Us</a>
                                    </li>
                                    <li>
                                        <a href="#" class="editContent"
                                           style="outline: none; cursor: inherit;">About Us</a>
                                    </li>
                                </ul>
                            </div>
                            <!-- social icons -->
                        </div>
                        <div class="col-md-4 footer-grid_section_w3layouts my-md-0 my-5">
                            <h3 class="footer-title text-uppercase text-wh mb-lg-4 mb-3 editContent"
                                style="outline: none; cursor: inherit;">Contact Info</h3>
                            <div class="contact-info">
                                <div class="footer-address-inf my-4">
                                    <h4 class="ad-info mb-2 editContent"
                                        style="outline: none; cursor: inherit;">Email </h4>
                                    <p class="editContent" style="outline: none; cursor: inherit;">
                                        <a href="mailto:info@example.com">info@example.com</a></p>
                                </div>
                                <div class="footer-address-inf">
                                    <h4 class="ad-info mb-2 editContent"
                                        style="outline: none; cursor: inherit;">Location</h4>
                                    <p class="editContent" style="outline: none; cursor: inherit;">
                                        New York City</p>
                                </div>
                            </div>
                        </div>


                    </div>

                </div>
            </div>
        </div>
    </footer>
    <!-- //footer -->
    <div class="cpy-right py-3">
        <div class="container">
            <div class="row">
                <p class="col-md-10 text-left">© 2019 DjangoMovie. All rights reserved | Design by
                    <a href="https://djangochannel.com"> DJANGO SCHOOL.</a>
                </p>
                <!-- move top icon -->
                <a href="#home" class="move-top text-right col-md-2"><span
                        class="fa fa-long-arrow-up" aria-hidden="true"
                        style="outline: none; cursor: inherit;"></span></a>
                <!-- //move top icon -->
            </div>
        </div>
    </div>
</div>

movies/templates/movies/base.html
{% extends 'base.html' %}
{% block content %}
        <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
            <div class="container-fluid py-md-3">
                <div class="row">
                {% include 'include/sidebar.html' %}
                {% block movie %}
                    {% endblock movie %}

                </div>
            </div>
        </section>
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% block movie %}
                <div class="left-ads-display col-lg-8">
                    <div class="row">
                        <div class="desc1-left col-md-6">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="desc1-right col-md-6 pl-lg-4">
                            <h3 class="editContent" style="outline: none; cursor: inherit;">
                                {{ movie.title }}
                            </h3>
                            <h5 class="editContent"></h5>
                            <ul>
                                <li style="list-style: none"><span><b>Год:</b> {{ movie.year }}</span></li>
                                <li style="list-style: none"><span><b>Страна:</b> {{ movie.country }} </span>
                                </li>
                                <li style="list-style: none"><span><b>Слоган:</b>{{ movie.tagline }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in movie.directors.all %}
                                        {{ director.name }}</span></li>
                                {% endfor %}
                                <li style="list-style: none"><span><b>Актеры:</b>
                                        {% for actor in movie.actors.all %}
                                        {{ actor.name }}
                                        {% endfor %}</span></li>
                                <li style="list-style: none"><span><b>Жанр:</b>
                                        {% for genre in movie.genres.all %}
                                        {{ genre.name }}
                                        {% endfor %}
                                </span>
                                </li>
                                <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>Бюджет:</b> {{ movie.budget }}</span></li>
                                <li style="list-style: none">
                                    <span><b>Сборы в США:</b> {{ movie.fees_in_usa }}</span></li>
                                <li style="list-style: none"><span><b>Сборы в мире:</b> {{ movie.fees_in_world }}</span>
                                </li>
                                <li style="list-style: none">
                                    <a href="#"><b>Рейтинг:</b>
                                    <span class="fa fa-star" aria-hidden="true"
                                          style="outline: none; cursor: inherit;"></span>
                                        <span class="fa fa-star" aria-hidden="true"
                                              style="outline: none; cursor: inherit;"></span>
                                        <span class="fa fa-star" aria-hidden="true"
                                              style="outline: none; cursor: inherit;"></span>
                                        <span class="fa fa-star" aria-hidden="true"
                                              style="outline: none; cursor: inherit;"></span>
                                        <span class="fa fa-star" aria-hidden="true"
                                              style="outline: none; cursor: inherit;"></span>
                                        <span class="editContent"
                                              style="outline: none; cursor: inherit;">5.0</span>
                                    </a>
                                </li>
                                <div class="share-desc">
                                    <div class="share">
                                        <h4 class="editContent"
                                            style="outline: none; cursor: inherit;">
                                            Share:</h4>
                                        <ul class="w3layouts_social_list list-unstyled">
                                            <li>
                                                <a href="#" class="w3pvt_facebook editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" class="w3pvt_twitter editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" class="w3pvt_dribble editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                        </div>
                    </div>
                    <div class="row sub-para-w3layouts mt-5">

                        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                            О фильме {{ movie.title }} </h3>
                        <p>
                            {% for image in movie.movieshots_set.all %}
                            <img src="{{ image.image.url }}" class="img-fluid" alt="{{ image.description }} ">
                            {% endfor %}
                        </p>
                        <p class="editContent" style="outline: none; cursor: inherit;"> {{ movie.description }}</p>
                        <p class="mt-3 italic-blue editContent"
                           style="outline: none; cursor: inherit;">
                            <iframe width="560" height="315"
                                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                                    frameborder="0" allow="accelerometer; autoplay;
                                                                           encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen>

                            </iframe>
                        </p>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="single-form-left">
                            <!-- contact form grid -->
                            <div class="contact-single">
                                <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;">02</span>Оставить отзыв</h3>
                                <form action="#" method="get" class="mt-4">
                                    <div class="form-group editContent"
                                         style="outline: none; cursor: inherit;">
                                        <label for="contactcomment" class="editContent"
                                               style="outline: none; cursor: inherit;">Ваш комментарий
                                            *</label>
                                        <textarea class="form-control border" rows="5"
                                                  id="contactcomment" required=""></textarea>
                                    </div>
                                    <div class="d-sm-flex">
                                        <div class="col-sm-6 form-group p-0 editContent"
                                             style="outline: none; cursor: inherit;">
                                            <label for="contactusername" class="editContent"
                                                   style="outline: none; cursor: inherit;">Имя
                                                *</label>
                                            <input type="text" class="form-control border"
                                                   id="contactusername" required="">
                                        </div>
                                        <div class="col-sm-6 form-group ml-sm-3 editContent"
                                             style="outline: none; cursor: inherit;">
                                            <label for="contactemail" class="editContent"
                                                   style="outline: none; cursor: inherit;">Email
                                                *</label>
                                            <input type="email" class="form-control border"
                                                   id="contactemail" required="">
                                        </div>
                                    </div>
                                    <button type="submit"
                                            class="mt-3 btn btn-success btn-block py-3"
                                            style="outline: none; cursor: inherit;">Отправить
                                    </button>
                                </form>
                            </div>
                            <!--  //contact form grid ends here -->
                        </div>
                        <div class="media py-5">
                            <img src="bundles/images/te2.jpg" class="mr-3 img-fluid" alt="image"
                                 style="outline: none; cursor: inherit;">
                            <div class="media-body mt-4">
                                <h5 class="mt-0 editContent"
                                    style="outline: none; cursor: inherit;">Daniel Doe</h5>
                                <p class="mt-2 editContent" style="outline: none; cursor: inherit;">
                                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                                    scelerisque ante sollicitudin. Cras purus odio, vestibulum in
                                    vulputate at, tempus viverra turpis.
                                </p>
                                <div class="media mt-5 editContent"
                                     style="outline: none; cursor: inherit;">
                                    <a class="pr-3" href="#">
                                        <img src="bundles/images/te1.jpg" class="img-fluid "
                                             alt="image" style="outline: none; cursor: inherit;">
                                    </a>
                                    <div class="media-body">
                                        <h5 class="mt-0 editContent"
                                            style="outline: none; cursor: inherit;">Leia Organa</h5>
                                        <p class="mt-2 editContent"
                                           style="outline: none; cursor: inherit;"> Cras sit amet
                                            nibh libero, in gravida nulla. Nulla vel metus
                                            scelerisque ante sollicitudin. Cras purus odio,
                                            vestibulum in vulputate at, tempus viverra turpis. Fusce
                                            condimentum nunc ac nisi vulputate fringilla..</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
{% endblock movie %}